language: python
python:
    - 2.6
    - 2.7
    - 3.2
    - 3.3
install:
    - pip install --upgrade 'setuptools>=1.4'
    - pip install --upgrade 'zc.buildout>=2.2.1'
    - buildout bootstrap
    - ./bin/buildout
script:
    - ./bin/test -vvv
notifications:
    email: false
